# Generated by Django 3.2.5 on 2021-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap', models.CharField(max_length=200)),
                ('ledger', models.CharField(max_length=200)),
                ('manufacture', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('base_km', models.CharField(max_length=200)),
                ('rto', models.CharField(max_length=200)),
                ('model_year', models.CharField(max_length=200)),
                ('chassis', models.CharField(max_length=200)),
                ('fuel_type', models.CharField(max_length=200)),
                ('old_vehicle', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
